name: goCrypt Release Management

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read version
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version
      - name: Get commit message
        id: log
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.package.outputs.content }}
          release_name: Release ${{ steps.package.outputs.content }}
          body: |
            Release against tag ${{ steps.package.outputs.content }} - ${{ steps.log.outputs.message }}
          draft: false
